### ISSUE TITLE
Player can't select a save point from main menu

### ISSUE THREAD

**Issue by David-Freund** [KendallBreivogel/SmokingGunGGJ2022#1]
The "new game" button on the main menu starts the game from the last saved checkpoint for the player instead of starting at the beginning. We need to add a checkpoint selection from the main menu and have the new game button clear the user data to actually start from the beginning.

**Comment by KendallBreivogel** [comment]
Done, needs testing

**Comment by David-Freund** [comment]
new system appears to have fixed the issue
